### ISSUE TITLE
Clarification on uploaded data

### ISSUE THREAD

**Issue by Anagmate** [covid19cz/erouska-android#144]
Hi,
I'd like to ask for clarification for how the data upload and matching process works.

When I first open the app, I'm supposed to enter my phone number, which is then uploaded to the backend database to allow local services to contact me if deemed necessary. In the FAQ, you say that on the backend, the health workers are able to get the phone number for any ID uploaded from the device of somone who tested positive for COVID-19. How is this matching done? You say that all interaction data are only stored locally, but the backend matching implies that all my generated IDs are uploaded, which I'd consider a major privacy violation.

Questions:
1. Are the user's generated temporary IDs uploaded to the backend during normal use, and associated with his phone number?
2. When someone uploads his contact data, how does the backend determine phone numbers of the people he came in contact with?
3. If someone had access to the backend (hacker/government officials), could he read phone numbers of people around him based on the IDs received from his surroundings using Bluetooth?

Thanks in advance for clarification.

**Comment by simekadam** [comment]
Hi thanks for the great questions: 
1. It's actually the backend who generates user ids. 
2. Because of the backend has all the identifiers it can match the uploaded identifiers to other users numbers.
3. Yes

I touched on why the system works like this (and why is it necessary) in https://github.com/covid19cz/erouska-android/issues/143
Please note that "government" has no direct access to our backend and it can only query contacts for individual numbers. And all uploaded data is automatically deleted no later than 6 hours after its uploaded.

**Comment by davidvavra** [comment]
Thanks Adam for answering, closing the issue.
