### ISSUE TITLE
Configuration too complicated for a regular user

### ISSUE THREAD

**Issue by Yanisin** [covid19cz/erouska-android#186]
I consider myself a "bit more" skilled then an average user and still it took me quite some time to set up the phone so the application stays running and logging. For example my girlfriend didn't manage that and I see her phone in my log only if she opens the app and some time after that.
Normal user will not go in the configuration and set anything at most he will be willing to tap that your app is allowed to set thus.
Thus.. I think the usability of the application is really doubtful if you consider that the average user will not be visible most of the time (I suppose normal people will just install and forget).

**Comment by davidvavra** [comment]
We know about this, we work on making the guides easier with screenshots etc. It's hard, every manufacturer and version of Android is different, manufacturers are breaking Android apps in non-standard ways. There is a whole website about this: https://dontkillmyapp.com It's source of our guides. I'm closing this, because it's not Android app issue, we will update guides on backend.
