### ISSUE TITLE
Bluetooth security flaws

### ISSUE THREAD

**Issue by saboteurspk** [covid19cz/erouska-android#187]
As eRouška uses Bluetooth as proximity sensor, all security flaws for Bluetooth on Android should be seriously evaluated and actions to ensure user security taken.

A lot of Android devices don't get any update even two years after device release and many people use quite old phone. E.g. my current phone has latest google security patch from October 5, 2017.

User should be informed that his device is missing security patches.

In last 3 years there were quite serious bugs:
[BlueBorne](https://www.armis.com/blueborne/)
[BlueFrag](https://www.andreafortuna.org/2020/02/13/bluefrag-cve-2020-0022-a-critical-bluetooth-vulnerability-in-android/)

Both can lead to silent execution of arbitrary code by attacker on users device.
There are probably more bugs patched in last years, those are just that I'm awere of.

**Comment by jendakol** [comment]
Hello,  
the situation as you describe is very unfortunate and we're aware of it.   

Unfortunately, you have basically two options when doing _this_ thing: go with either GPS or BT. Both technologies have their own pros and cons, for us the winner is Bluetooth - it's just the best from our POV, still being aware of its problem.  

However, BT is a very common technology that many of us actually use every day - headphones, smartwatches and bands, car audio sets; so we think we actually might not increase number of people using BT _that much_ *and* we're also not aware of anyone would actually use these bugs in a big scale. Moreover, many of similar apps all over the world goes the same way - we're far from being alone.  

Let's wish us all success.

**Comment by saboteurspk** [comment]
Please reopen this issue.

There are some steps in app, that could and should be done. We were discussing it on Twitter with Adam Šimek and Roman Pichlík today.
See e.g. [Twitter link](https://twitter.com/simekadam/status/1251123707843674112)
Application should check, if device has latest security patches. If not, show user some warning

The older vulnerability can be used to:
**Control of devices, access corporate data and networks, penetrate secure “air-gapped” networks**, and spread malware laterally to adjacent devices.

It's like spreading a disease. Tools for using this bug to attack an device are available!

> However, BT is a very common technology that many of us actually use every day - headphones, smartwatches and bands, car audio sets; so we think we actually might not increase number of people 

You have to have some data to be able to say something like that. 

>  and we're also not aware of anyone would actually use these bugs in a big scale. 

So we will start to thing about defensive actions after we know that somebody is using those bugs?

> Moreover, many of similar apps all over the world goes the same way - we're far from being alone.

If somebody does it wrong, we don't need to copy that behavior

**Comment by jendakol** [comment]
Well, I've read through the discussion, it seems my colleagues have the same opinion as I do.

I can't imagine displaying a warning to most of our users where 90% of them won't understand it and/or will feel offended that we recommend them to buy a new phone. Should we recommend them to buy a new phone just because of eRouška? I don't think so, that's like "please, uninstall this application, we think your phone is a brick" message.  
And we're trying to achieve something by this application, remember?  
Are you sure the current situation is not worth taking this risk?

> It's like spreading a disease. Tools for using this bug to attack a device are available!

Maybe, but Google and Apple are trying to achieve similar things with a similar technology, do *they* spread the disease too?

> So we will start to think about defensive actions after we know that somebody is using those bugs?

There's no defensive action we can take now, we just can't update phones of our users. It'd be great, wouldn't it...

> You have to have some data to be able to say something like that.

I do have something to support claim "many of us actually use every day - headphones, smartwatches and bands, car audio sets"? I don't claim any specific numbers, I just say it's very common. Did you look around yourself recently?

> If somebody does it wrong, we don't need to copy that behavior

All right. I believe your critics is constructive, so... What's your solution to this situation - what technology would **you** use for this?

**Comment by Kobzol** [comment]
https://geomarketing.com/beacon-roundup-what-percentage-of-americans-leave-bluetooth-on-anyway it seems that it's about 50 % of users, of course it will vary a lot between countries.

You're right that BT has vulnerabilities, but we have to be realistic here. There are tens of thousands of Android applications using Bluetooth and I doubt that you will find a lot of them screaming "Don't use this app, it might be dangerous" at you everytime you start them. You would have to do that for every app with a vulnerability, which is pretty much anything that uses the internet, Bluetooth, GPS etc. I suspect that you will find *some* potential vulnerability in a technology used by this app in pretty much any phone. So if we went with this approach the app couldn't be used by anyone.

If there are some easy steps that we can make to protect or warn the users, we can think about them, but this application will not solve global Bluetooth problems and it definitely needs Bluetooth to function properly, so this is a risk that we simply have to take.

**Comment by saboteurspk** [comment]
> I can't imagine displaying a warning to most of our users where 90% of them won't understand it and/or will feel offended that we recommend them to buy a new phone. Should we recommend them to buy a new phone just because of eRouška? I don't think so, that's like "please, uninstall this 

I can't imagine to recommend this application to any user with older phone. From ethical point of view user has right to be informed about dangers that are connected with usage of this application.
To hide behind other companies that do the same doesn't solve the ethical problem.
We have two threats: disease and cyber threat.
You don't have any right to make choice among them for the user.

> Maybe, but Google and Apple are trying to achieve similar things with a similar technology, do they spread the disease too?

If their solution will be similar with the same flaws, then yes.

> There's no defensive action we can take now, we just can't update phones of our users. It'd be great, wouldn't it...

Defensive action is to let the user decide

> it seems that it's about 50 % of users, of course it will vary a lot between countries.

This data is not trustworthy. You can find other sites saying:

> Younger users are significantly more likely to have Bluetooth turned on. Users with connected devices are very likely to have Bluetooth on - for example most drivers or those with hands-free headsets. North American consumers tend to have some of the higher rates of Bluetooth while rates go as low as about 15-20% in Eastern Europe and Russia.

And younger users probably use newer phones
You should have done a proper analysis of this topic in the first steps, but you probably didn't. 
I saw some people asking about older phones than Android 5. So how many users with security holes are using this app? You probably have statistics from Firebase about device info like Android version.

> I suspect that you will find some potential vulnerability in a technology used by this app in pretty much any phone. So if we went with this approach the app couldn't be used by anyone.

It realy makes difference to have device with known flaws and unpublished flaws.
Everybody knows then when exploit is published, you can quite often download sources of exploit demonstration.

You can still decide that you will care about users.
What will you do, if some users will be attacked and will be harmed? Will you just say, that it was his fault? Let's not play God games.

**Comment by Kobzol** [comment]
You are right, we didn't do a thorough analysis of Bluetooth vulnerabilities, that is out-of-scope for this application and we simply do not have time for that. We do not have Firebase analytics for privacy reasons, but the minimum API for our application is 21, so there are no older phones than Android 5.0 using our application.

You say that we should let the users decide, but the simple truth is that the overwhelming majority of users have no idea what a vulnerability, exploit, or even Bluetooth is. If you show them such warning it will only intimidate them, in most cases for no good reason.

Do you see warnings that someone can exploit your phone using the web when you open Google Chrome for the first time? Or that someone can exploit GPS when you open navigation maps? You don't. Because some users would immediately uninstall the app, without actually understanding the real threat level. And then they would download a different app which uses the same technology but doesn't scare them with such warnings.

If we could show the users a button that would magically patch their OS with Bluetooth fixes, we would not hesitate to do it. But as you probably know, getting fixes, or any kind of software updates is a painfully slow process in the Android world. So we cannot do anything about the vulnerabilities, but we also do not consider them to be critical. Therefore we do not warn the users explicitly and I don't think that it is the role of this app to show such a warning when other applications do not do it.

**Comment by saboteurspk** [comment]
>  So we cannot do anything about the vulnerabilities, but we also do not consider them to be critical.

Google and others did. Both bugs were marked as critical and for a good reason.

> Because some users would immediately uninstall the app, without actually understanding the real threat level. 

The threat level here is full device control with easy downloadable software to attack the device. The only worse level could be the same but from any distance to device. Now you are limited to few meters. Ask anybody on the street question: "Hey do you want to be hacked?"
And you probably are aware of cyber attacks on czech hospitals, right?

You simply want push the users to install this app because you need them to make this app work.
The benefit of this app is disputable, the threat is real.

**Comment by Kobzol** [comment]
Yes, the OS vendor obviously has to fix the vulnerability, but that doesn't mean that this vulnerability is being actively exploited in the wild and that it is critically dangerous to common users. There are thousands of Android apps using Bluetooth that are not warning their users of potential vulnerabilities, same as for example web browsers do not warn users that there are exploits on the web. Do you also have a problem with them or do you only have a problem with this app? In my opinion it's not the duty of the apps to warn users of such things. You couldn't use any app if you had to scroll through any potential vulnerability that could be caused by using the app, there is a myriad of such vulnerabilities for every app on the Play Store.

We do not need to make this app work, it would be ideal if this app would not have to exist at all. We do not know if this app will make any difference, but we think that it could, so we have built it to help.

Recommending users to "buy a new device", as you have stated on Twitter, is simply an unrealistic solution to the problem that you mention. If you have a different solution, let us know and we will think about it. Or better yet, send us a pull request and we can discuss it.

**Comment by saboteurspk** [comment]
> There are thousands of Android apps using Bluetooth that are not warning their users of potential vulnerabilities, same as for example web browsers do not warn users that there are exploits on the web. Do you also have a problem with them or do you only have a problem with this app?

Yes, I do.
But if you are asking this way, eRouska is now **made for government** and you are trying to spread it to **milions of users**. It's not some ordinary app. If private company doesn't want to warn user, it's theirs choice (still bad one).

> Recommending users to "buy a new device", as you have stated on Twitter, is simply an unrealistic solution

This was variant for really old devices like Android 5. For newer you can just inform the user, to search update for his OS.

> We do not need to make this app work

I said that you are pushing users. And there is a lot of evidence for that.
![image](https://user-images.githubusercontent.com/42414933/79828892-0597da80-83a2-11ea-820a-75f08bb9dd55.png)

**Comment by jendakol** [comment]
@saboteurspk I see you still didn't propose any better solution than what we've used; why so?

**Comment by saboteurspk** [comment]
I have proposed two fair solutions.
Next, if you find a problem with something, it's not your responsibility, job or commitment to find a solution. It was your job to do analysis and take appropriate action (which you didn't and which you don't want to do).

So to sum up your attitude:
You are now aware critical security holes in your infrastructure (end devices are part of it for sure)
You are doing application for government and still don't feel responsibility for citizens and whole infrastructure in CZ (that can be penetrated with some devices with priviledged access to some network). 
You know that in some companies this app is on black list because of this security holes.

And yet you ask me for solution?
You say that you do not need to make this app work, but you don't want to lose any user at the same time?
Application is supported on **Android 5** devices. We all know  that those devices don't have necessary security patches. 
Why don't you require at least **Android 8**? Because you don't want to lose users? But you don't push the app?

Google has marked both bugs as critical.
But he is not just sayin that to users. It's targeted to developers as well. Users usualy are not aware of this, developers are.

How this all is consistent with 
[Závazek datové důvěry](https://www.covid19cz.cz/covid19-cz/zavazek-datove-duvery)

> Toto vnímáme jako velké ohrožení svobody a soukromí lidí a nemyslíme si, že je to v souladu s principy naší evropské demokratické kultury a k takovémuto řešení nechceme přispívat.

This app is definitely adding danger to privacy violation

**Comment by Kobzol** [comment]
Yes, we want as many users as possible to install this app for it to be as effective as possible. But we are not pushing (=forcing) users to install the application. Requiring Android 8 would prevent a lot of users from using the app. We consider that a problem, you obviously do not. Even newer Androids have security holes (https://www.androidpolice.com/2020/02/08/bluefrag-security-vulnerability-allows-code-execution-over-bluetooth-on-some-android-devices/).

As I said before, if we didn't allow this app to be installed on vulnerable devices, there would be no usable devices left. It's sad, but that's how it is.

We are now discussing the option of mentioning possible BT vulnerabilities in our FAQ, but we cannot really do anything useful in the app - most users either do not know how to update their OS (this could be solved with guides) or their phone has no OS updates available (this cannot be solved by us).

**Comment by jendakol** [comment]
I see, so you **don't** have any other solution.

> Why don't you require at least Android 8?

You've shown very well you just don't understand what's going on here. We need to spread this application to as many people as possible, even requiring Lollipop is a target of criticism by some users.

I think it's time to end this.  
I don't want to repeat myself and please, please don't repeat yourself either.  You've explained what bothers you, we've explained why your suggestions are not acceptable. I see no point in discussing this again and again unless you come with some real suggestions on how to make **everyone** happy.  

Bye.

**Comment by saboteurspk** [comment]
> You've shown very well you just don't understand what's going on here. We need to spread this application to as many people as possible, even requiring Lollipop is a target of criticism by some users.

I understand it very well. Cheap words. 

>  Even newer Androids have security holes

I've told you about BlueFrag just in the first message of this issue.

> We are now discussing the option of mentioning possible BT vulnerabilities in our FAQ, but we cannot really do anything useful in the app

Hmm just to add it to FAQ (that nearly nobody will read) takes so much effort? Sorry, you are lying.
So play your God games.
It was obvious you will act like this when you've closed this issue without any discussion. 
This is 1) rude 2) unprofessional.

**Comment by jendakol** [comment]
You created this "issue" after you had been already told there will most probably be no action in this way on Twitter, so what did you expect? :wink:  
I've closed it with an explanation, repeating reasons you already knew.

Rude is accusing us of lying. Save it for yourself (_"nechte si to od cesty"_).

Next time, maybe spend more time coming with some new, functional and flawless technical solution, instead of convincing us how bad is the one we used (even though we've clearly stated we know it).

**Comment by Kobzol** [comment]
I know that you mentioned BlueFrag, but what do you want us to do about it? There are vulnerabilities for possibly all Android versions < 10, probably there are some even for Android 10, just undisclosed yet. Disabling the app on these versions would mean that almost no one could use the app. We cannot fix the problem within our app and most of our users cannot evaluate the potential risk if we showed a warning.  

I'm not sure what do you mean by us lying. Adding things to FAQ doesn't take a lot of effort of course. I have conveyed your worries in a meetup today, the response is that we will add a mention of this issue to the FAQ. You can join the decision process on the Covid19 Slack (I can invite you if you want), both the app and its processes are open source.

Your proposed solution was not deemed acceptable, because it would alienate a lot of users that could otherwise benefit from using this app, but in return it wouldn't really solve anything. Some users would be needlessly alienated and most of them couldn't fix the problem in any way because their phones would not offer the required update.

**Comment by Kobzol** [comment]
We have added a question about Bluetooth security to the FAQ: https://erouska.cz/caste-dotazy (Je Bluetooth dostatečně bezpečná technologie?)

**Comment by saboteurspk** [comment]
> eRouška FAQ:
Je Bluetooth dostatečně bezpečná technologie?
Bluetooth je dnes běžně rozšířená a podporovaná komunikační technologie pro propojení zařízení s dalšími periferiemi, jako jsou bezdrátová sluchátka, reproduktory, chytré náramky nebo hodinky. Vzhledem k tomu, že na další podpoře jejího použití v aplikacích trasujících rizikové kontakty spolupracují i Apple a Google, jsme přesvědčení, že jsme pro eRoušku zvolili správně. Je však potřeba říct, že úplně každá technologie je zranitelná. I proto všem uživatelům doporučujeme, aby operační systém a aplikace ve svém telefonu pravidelně aktualizovali. Aktualizace totiž mohou obsahovat důležité bezpečnostní záplaty.

So now you are definitely lying to people?
You know that this technology is unsafe and yet you are not ashamed to say that you have chosen the right technology?

You know, that many of your users don't have latest security patches = those are vulnerable and Bluetooth is dangerous option for them.
You know that penultimate update is essential and yet you write: "Updates may contain important security patches".
You know that just few of them will read this FAQ.

You didn't make things better by this FAQ, just worse. The only one sentence that drives user to right direction is "We recommend the user to install latest updates".
But we all know that latest OS updates in Android don't mean latest security patches.

**Comment by Kobzol** [comment]
Every technology has vulnerabilities. If the presence of a vulnerability instantly disqualifies some technology in your eyes, you should stop using computers and mobile phones, there's just no solution for this.

Yes, Bluetooth is the right technology, because it's the only current one that can support tracing properly and that is supported on a large number of phones. Every other tracing app is using it and same as us, they have evaluated that the benefits outweight the risks.

As you said, we cannot do anything about the missing updates. We gave our users a recommendation, that is all we can do for now.
