### ISSUE TITLE
Google Exposure Notification API

### ISSUE THREAD

**Issue by PiTRiS87** [covid19cz/erouska-android#236]
Is there a plan to implement Google Exposure Notification API, similar to apple exposure notification, that seems to be already in works?
https://developers.google.com/android/exposure-notifications/exposure-notifications-api

**Comment by davidvavra** [comment]
Yes, we are implementing it, it's in progress (check `develop` branch). It's basically app rewrite, lot of work.

**Comment by brozkeff** [comment]
Are various apps using Exposure Notification API mutually compatible so that future Czech eRouška 2.0 beacons can be received by German Corona-Warn-App and vice versa? Can I already install the German app if I trust it and will it work anywhere where countries adopt Exposure Notification API in their national apps?

**Comment by davidvavra** [comment]
@brozkeff There is pan-european forum on sharing data between countries who use Exposure Notifications API. We are part of it, in the future we will share data. But not with the first release.

**Comment by davidvavra** [comment]
v2 version of the app with Exposure Notifications API is out!
